version: '3.5'

services:
  ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.9.1
    restart: always
    volumes:
      - ${HTTP_VOLUME:-/tmp/nginx}/conf.d:/etc/nginx/conf.d
      - ${HTTP_VOLUME:-/tmp/nginx}/vhost.d:/etc/nginx/vhost.d
      - ${HTTP_VOLUME:-/tmp/nginx}/html:/usr/share/nginx/html
      - ${HTTP_VOLUME:-/tmp/nginx}/certs:/etc/nginx/certs:rw
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: foxtrot_http
      NGINX_DOCKER_GEN_CONTAINER: foxtrot_docker_gen
      DEBUG: ${DEBUG:-false}
    logging:
      driver: ${SSL_LOG_DRIVER:-json-file}
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-2m}
        max-file: ${LOGGING_OPTIONS_MAX_FILE:-10}
    networks:
      net:
        aliases:
          - foxtrot_ssl

  http:
    image: nginx
    container_name: foxtrot_http
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    restart: always
    ports:
      - "${IP:-0.0.0.0}:${HTTP_PORT:-80}:80"
      - "${IP:-0.0.0.0}:${HTTP_PORT:-443}:443"
    volumes:
      - ${HTTP_VOLUME:-/tmp/nginx}/conf.d:/etc/nginx/conf.d
      - ${HTTP_VOLUME:-/tmp/nginx}/vhost.d:/etc/nginx/vhost.d
      - ${HTTP_VOLUME:-/tmp/nginx}/html:/usr/share/nginx/html
      - ${HTTP_VOLUME:-/tmp/nginx}/certs:/etc/nginx/certs:ro
      - ${HTTP_VOLUME:-/tmp/nginx}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: ${HTTP_LOG_DRIVER:-json-file}
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-4m}
        max-file: ${LOGGING_OPTIONS_MAX_FILE:-10}
    networks:
      net:
        aliases:
          - foxtrot_http

  docker_gen:
    image: jwilder/docker-gen:0.7.3
    container_name: foxtrot_docker_gen
    depends_on:
      - ssl
      - http
    entrypoint: /bin/sh -c
    command: ["/usr/local/bin/docker-gen -notify-sighup foxtrot_http -watch -wait 30s:60s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"]
    restart: always
    volumes:
      - ${HTTP_VOLUME:-/tmp/nginx}/conf.d:/etc/nginx/conf.d
      - ${HTTP_VOLUME:-/tmp/nginx}/vhost.d:/etc/nginx/vhost.d
      - ${HTTP_VOLUME:-/tmp/nginx}/html:/usr/share/nginx/html
      - ${HTTP_VOLUME:-/tmp/nginx}/certs:/etc/nginx/certs:ro
      - ${HTTP_VOLUME:-/tmp/nginx}/htpasswd:/etc/nginx/htpasswd:ro
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/tmp/docker.sock:ro
      - ./config/http/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${DOCKER_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${LOGGING_OPTIONS_MAX_SIZE:-2m}
        max-file: ${LOGGING_OPTIONS_MAX_FILE:-10}
    networks:
      net:
        aliases:
          - foxtrot_docker_gen
